### ISSUE TITLE
Add `lazy val root ...` will break sbt commands

### ISSUE THREAD

**Issue by guizmaii** [Fabszn/scaffolding-plugin-lagom#14]
In the documentation, you say to add:

```
lazy val root = (project in file("."))
    .enablePlugins(LagomScaffoldingPlugin)
```

But because of that, some sbt commands will not be launched as expected.

For example, if I launch `sbt test` **without** the `lazy val root...` on my project, it'll launch tests for every modules (I have 4 API/impl modules named `toto`, `tata`, `tutu`, `titi` and one `utils` module):

```
> test
[info] Updating {file:/Users/Jules/colisweb/workspace/lagom/}toto-api...
[info] Updating {file:/Users/Jules/colisweb/workspace/lagom/}utils...
[info] Updating {file:/Users/Jules/colisweb/workspace/lagom/}tata-api...
[info] Updating {file:/Users/Jules/colisweb/workspace/lagom/}tutu-api...
[info] Updating {file:/Users/Jules/colisweb/workspace/lagom/}titi-api...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving org.joda#joda-convert;1.8.1 ...

... (a lot of logs)


[info] Compiling 7 Scala sources to /Users/Jules/colisweb/workspace/lagom/toto-impl/target/scala-2.11/classes...
[success] Total time: 64 s, completed 16 sept. 2016 17:22:16
```

Now, if I launch `sbt test` **with** `lazy val root...`:

```
> test
[info] Updating {file:/Users/Jules/colisweb/workspace/lagom/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[success] Total time: 1 s, completed 16 sept. 2016 17:31:00
```

To correct that, a (boring, but maybe the only one) solution is to declare root project aggregates: http://www.scala-sbt.org/1.0/docs/Multi-Project.html#Aggregation

That's what Lagom people do, see:
https://github.com/lagom/lagom/blob/master/build.sbt#L183
https://github.com/lagom/lagom/blob/master/build.sbt#L217

At Colisweb, our solution is just to comment/uncomment the `lazy val root...` line because we are too lazy to maintain a project list ;)

**Comment by Fabszn** [comment]
This issue is fixed with 1.0.0-M3 version. 
Root project is not required. 
Just add the plugin into plugin.sbt and that's all.
