### ISSUE TITLE
Scala API support

### ISSUE THREAD

**Issue by jacobus** [Fabszn/scaffolding-plugin-lagom#15]
Hi Fabrice,

Great plugin, thanks!

Will you still be adding support for the Scala API?

Best,
Jack

**Comment by Fabszn** [comment]
Hi Jacobus,

Many thanks for your feedback. 

It would be great to add support of Scala API. But I read that Lagom's team will introduce a tool (based on SBT 0.13) that support the same purpose of this plugin. (for both maven and SBT)
Then I wondering me if this plugin will stay useful
Currently, I am under heavy workload. But when time become more quiet, I ll try to add support of Scala API.

Best,

Fabrice

**Comment by jacobus** [comment]
Thanks for the response Frabice. Yes, it would be great if the Lagom team
supports this functionality, but I have no idea when this will become
available. I'll still keep an eye on your project. It's very informative on
both Lagom and writing SBT projects.

Great work!

**Comment by Fabszn** [comment]
It is done :)
