### ISSUE TITLE
separate services into packages

### ISSUE THREAD

**Issue by kdevrou** [Fabszn/scaffolding-plugin-lagom#9]
Currently, all source files are all created in the same package. Having separate packages per service would  make it easier to keep things conceptually separated.

**Comment by Fabszn** [comment]
Hi @kdevrou,

Thanks for your feed-back.

To be sure to understand your point. 
When you speak about service, you mean Lagom service (sbt module) ? 
Actually, there is  an optional parameter on the  command line that allow to override the default value. 

did you see and/or try it? let me know if this parameter answers to this issue. 

regards

**Comment by kdevrou** [comment]
I see your point, I had only thought about the org parameter as a way to redefine the base organization. Your intention is to use it like this:

`newScalaService Home org:com.example.home`

This is most of what I was looking for, keeping services in separate packages.
